version: "3.1"
name: mavenwebapplication
services:
  mavenwebapp:
    image: dheeravathshiva/maven-web-application:1
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
    driver: bridge
volumes:
  mavenwebappvol
   driver: local

